### ISSUE TITLE
[Feature Request] Could You Expose an Option to Allow Duplicates?

### ISSUE THREAD

**Issue by TheCedarPrince** [rareitems/anki.nvim#4]
A use case I have is usually I have multiple cards that have the same sort field or same fields between cards. Currently, the plugin does not allow me to send cards with duplicate sort fields. Could you expose an option that allows one to send duplicates to Anki? 

Here is an example of two cards where I am prohibited from sending the second one:

Card 1

```
%%MODELNAME Math Definition Properties
%%DECKNAME Mathematics::Graph Theory
%%TAGS
%Object
Graph Isomorphism 
%Object
%Context

%Context
%Property
Isomorphic graph {{c1::complements}} must be {{c2::isomorphic}} 
%Property
```

Card 2

```
%%MODELNAME Math Definition Properties
%%DECKNAME Mathematics
%%TAGS
%Object
Graph Isomorphism
%Object
%Context

%Context
%Property
A graph is said to be {{c1::isomorphic}} if an {{c2::isomorphism}} exists between {{c3::two graphs}}
%Property
```

Otherwise, thanks for the wonderful plugin! I use this so much in graduate school and various studies. It makes automating or generating anki cards interactively so much nicer!

**Comment by rareitems** [comment]
Hello, thanks for kind words.

When I try to add a card in the way you specified (there is already a card in anki and then I try to add a card with the same sort field but to another deck) it works and it works like expected (AnkiConnect API says it should only check the target deck for duplicates). Not sure why it doesn't work for you.
But anyway I added an option to add "duplicates" since anki allows you add card with duplicate sort fields (always thought it would not do that). 
[Link to docs how to add cards with duplicates](https://github.com/rareitems/anki.nvim/blob/master/doc/anki.txt#L151) or with `:AnkiSendAllowDuplicate` command

If you have any ideas how to make this plugin better let me know.

**Comment by TheCedarPrince** [comment]
Hey, thank you so much for taking the time to add this feature in! I know that probably took some time so I deeply appreciate it. I already went ahead, used it, and it seems to be working great! I am now on my way to making even more math study cards and greater. :smile: 

But yea, interesting. Not sure why I was getting the error... Either way, have a great day!
